### ISSUE TITLE
RPL liefert Fehler bei Debian Bullseye

### ISSUE THREAD

**Issue by McAntwort** [pimanDE/settings2pi#1]
hab gestern einen neuen Pi mit Bullseye aufgesetzt, dabei ist mir Aufgefallen das alle Zeilen von RPL die nach ÄÖÜ und co ersetzt werden fehler liefern, danach ist die installation von PiHole geschrottet

```
echo "sommer" > ./test.txt
rpl "sommer" "frühling" ./text.txt
```

> 
> ```
> rpl: Replacing "sommer" with "frühling" (case sensitive; partial words matched)
> Traceback (most recent call last)
>   File /usr/bin/rpl"; line 413, in <module>
>     matches = replace(f, o, regex, old_str, new_str, encoding, filename)
>   File "/usr/bin/rpl", line 200, in replace
>     outstream.writ(joined_parts.encode(encoding=encoding))
> UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 2: ordinal not in range(128)
> ```

Mit Debian Buster geht alles wie es soll.

Wäre schön mal drüber zu schauen

//sorry, gehört zu translate2german

**Comment by McAntwort** [comment]
bitte so abändern

`rpl --encoding UTF-8 <suche> <ersetze> <file>`

danke

**Comment by pimanDE** [comment]
Hallo McAntwort,

danke für Deinen Hinweis.

Grüße
pimanDE
